# pytorch_lightning==1.8.1
seed_everything: 1138
trainer:
  logger: 
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: "UNET-CTLung"
      project: "AI_UNet_CTScans"
      log_model: false
      dir: lightning_logs
      notes: IOU, Dice & Acc, CT Lung.
  enable_checkpointing: true
  enable_progress_bar: true
  max_epochs: 1000
  
  auto_lr_find: true
  num_sanity_val_steps: 2

  log_every_n_steps: 50
  enable_model_summary: true

  accelerator: gpu
  devices:
    - 0
  amp_backend: apex
  # precision: 32

model:
  batch_size: 8
  learning_rate: 1e-4
  num_channels: 1
  num_classes: 1
  # bilinear: false
  verbose: false

data:
  class_path: dataset_2.CTLungDataloader
  init_args:
    dataset_dir: /ssd_data/CT_Lung/
    batch_size: 8
    num_workers: 8
    augment: true
    shuffle: true
    drop_last: true
    persistent_workers: false

ckpt_path: null