# pytorch_lightning==1.8.1
seed_everything: 1138
trainer:
  logger: true
  enable_checkpointing: true
  enable_progress_bar: true
  max_epochs: 100
  
  auto_lr_find: true
  num_sanity_val_steps: 2

  log_every_n_steps: 50
  enable_model_summary: true

  accelerator: gpu
  devices:
   - 2
  amp_backend: apex
  precision: 32

model:
  batch_size: 8
  learning_rate: 0.00001
  num_channels: 1
  num_classes: 47
  bilinear: false
  verbose: false

data:
  dataset_dir: /ssd_data/IRCAD/3Dircadb1
  batch_size: 8
  num_workers: 32
  shuffle: true
  drop_last: true

ckpt_path: null